mkdir -p .github/workflows

cat > .github/workflows/test-qnap-custom.yml << 'EOF'
name: Test QNAP Custom Scripts

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-qnap-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Simuliere UPS Device
        run: |
          mkdir -p /tmp/sys/bus/usb/devices/mock1
          echo "0764" > /tmp/sys/bus/usb/devices/mock1/idVendor
          echo "BR1200ELCD" > /tmp/sys/bus/usb/devices/mock1/product

      - name: Test QNAP Detection Script
        run: |
          chmod +x custom/dui_qnap_custom.sh
          ./custom/dui_qnap_custom.sh | grep -q "1" && echo "PASS" || (echo "FAIL" && exit 1)
EOF


