name: Test USB Detection and Slack Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  usb-detection-test:
    name: Simulate CyberPower USB Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup mock USB directory
        run: |
          mkdir -p /tmp/sysbus/devices/mock-cyberpower
          echo "CyberPower UPS" > /tmp/sysbus/devices/mock-cyberpower/product

      - name: Modify detection script to use mock path
        run: |
          sed -i 's/\/sys\/bus\/usb/\/tmp\/sysbus/' common/detect_usb_id.sh

      - name: Run detection script
        run: |
          chmod +x common/detect_usb_id.sh
          ./common/detect_usb_id.sh | grep -qi cyberpower && echo "PASS" || (echo "FAIL"; exit 1)
