name: Run UPS Scripts Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run USB detection script
        run: |
          chmod +x common/detect_usb_id.sh
          ./common/detect_usb_id.sh || echo "No USB found or test-only output"
