version: '3.9'

services:
  ups-toolkit:
    build: .
    container_name: ups_toolkit_local
    volumes:
      - ./logs:/app/logs
    command: [ "bash", "-c", "./common/detect_usb_id.sh && sleep infinity" ]
#run with 
#docker-compose build
#docker-compose up -d